ascii 8 "Signature"
hex 4 "Revision"
uint32 "Header Size"
hex 4 "Header CRC"
uint32 "Reserved"
uint64 "Current LBA"
uint64 "Backup LBA"
uint64 "First Usable LBA"
uint64 "Last Usable LBA"
uuid "Disk GUID"
uint64 "Partitions LBA"
uint32 "Num Partitions"
uint32 "Entry Size"
hex 4 "Partitions CRC"
hex 420 "Reserved"
