name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set Xcode Version
      run: sudo xcode-select -s /Applications/Xcode_16.2.app
    - name: Build Hex Fiend
      run: xcodebuild -scheme Release
    - name: Build Tests
      run: xcodebuild build-for-testing -scheme "Framework CI Tests"
    - name: Run Tests
      run: xcodebuild test-without-building -scheme "Framework CI Tests"
    - name: Install Doxygen
      run: brew install doxygen
    - name: Build Documentation
      run: xcodebuild -scheme "Documentation Generation"
