name: CI

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Hex Fiend
      run: xcodebuild -scheme Release
    - name: Build Documentation
      run: xcodebuild -scheme "Documentation Generation"
