name: CI

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Hex Fiend
      run: xcodebuild -scheme Release
    - name: Run Tests
      run: xcodebuild test -scheme "Framework CI Tests"
    - name: Install Doxygen
      run: brew install doxygen
    - name: Build Documentation
      run: xcodebuild -scheme "Documentation Generation"
